import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import { readStartParam, telegramChallengeLink } from './platform';

type WebApp={initData?:string;initDataUnsafe?:{user?:{first_name?:string}};BackButton?:{show():void;hide():void;onClick(fn:()=>void):void;offClick?(fn:()=>void):void};HapticFeedback?:{impactOccurred(x:string):void;notificationOccurred(x:string):void};themeParams?:Record<string,string>;requestFullscreen?():void;openTelegramLink?(url:string):void;shareMaxContent?(params:{text:string;link?:string}):void};
declare global {interface Window {WebApp?:WebApp;Telegram?:{WebApp:WebApp}}}
type Platform='max'|'telegram'|'mock'; type Pack={slug:string;title:string;emoji:string;description:string;question_count:number;estimated_minutes:number}; type Question={position:number;text:string;options:string[];timeout_seconds:number}; type Game={id:number;score:number;correct_answers:number;question_count:number;current_question:Question|null}; type Mastery={category:string;seen:number;correct:number;percent:number};
const tg=()=>window.Telegram?.WebApp; const platform=(import.meta.env.VITE_PLATFORM||(tg()?'telegram':window.WebApp?'max':'mock')) as Platform; let session='';
const bridge={initData:()=>platform==='telegram'?tg()?.initData||'':window.WebApp?.initData||'',name:()=>platform==='telegram'?tg()?.initDataUnsafe?.user?.first_name||'Игрок':window.WebApp?.initDataUnsafe?.user?.first_name||'Игрок',back:(fn:()=>void,on:boolean)=>{const b=platform==='telegram'?tg()?.BackButton:window.WebApp?.BackButton;if(on){b?.show();b?.onClick(fn)}else b?.hide()},haptic:(ok:boolean)=>{const h=platform==='telegram'?tg()?.HapticFeedback:window.WebApp?.HapticFeedback;if(ok)h?.notificationOccurred('success');else h?.notificationOccurred('error')},fullscreen:()=>tg()?.requestFullscreen?.(),share:(text:string,token?:string)=>{const link=telegramChallengeLink(import.meta.env.VITE_TELEGRAM_BOT_USERNAME,token||'');if(platform==='max')window.WebApp?.shareMaxContent?.({text,link});else if(platform==='telegram'&&link)tg()?.openTelegramLink?.(`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent(text)}`);else navigator.share?.({text,url:link}).catch(()=>{})}};
const headers=():Record<string,string>=>platform==='mock'?{'X-Development-User':'10001','Content-Type':'application/json'}:{Authorization:`Bearer ${session}`,'Content-Type':'application/json'};
async function api(path:string,init?:RequestInit){const response=await fetch(path,{...init,headers:{...headers(),...(init?.headers||{})}});if(!response.ok)throw new Error(await response.text());return response.json()}

function App(){const [screen,setScreen]=useState<'home'|'catalog'|'game'|'result'|'profile'|'leaderboard'>('home');const [packs,setPacks]=useState<Pack[]>([]);const [game,setGame]=useState<Game|null>(null);const [feedback,setFeedback]=useState('');const [ready,setReady]=useState(false);const [name,setName]=useState(bridge.name());const [error,setError]=useState('');const [challengeCode,setChallengeCode]=useState('');const [mastery,setMastery]=useState<Mastery[]>([]);const [achievements,setAchievements]=useState<string[]>([]);const [leaders,setLeaders]=useState<{rank:number;name:string;score:number}[]>([]);const [seconds,setSeconds]=useState(30);
 const refreshPlayer=async()=>{const [player,progress,badges,board]=await Promise.all([api('/api/v1/me'),api('/api/v1/me/progress'),api('/api/v1/me/achievements'),api('/api/v1/leaderboard')]);setName(player.name);setMastery(progress.mastery);setAchievements(badges.items);setLeaders(board.items)};
 useEffect(()=>{const params=(platform==='telegram'?tg():window.WebApp)?.themeParams||{};for(const [key,value] of Object.entries(params))document.documentElement.style.setProperty(`--tg-theme-${key.replace(/_/g,'-')}`,value);document.documentElement.dataset.platform=platform},[]);
 useEffect(()=>{const load=async()=>{if(platform!=='mock'){const auth=await api(`/api/v1/auth/${platform}`,{method:'POST',body:JSON.stringify({init_data:bridge.initData()})});session=auth.access_token}const catalog=await api('/api/v1/quizzes');setPacks(catalog.items);await refreshPlayer();setReady(true);const p=readStartParam(location.search);if(p==='daily')await daily();else if(p.startsWith('challenge_'))await join(p.slice(10));else if(p==='leaderboard')setScreen('leaderboard')};load().catch(()=>setError('Не удалось подключиться к игре. Открой её из приложения ещё раз.'))},[]);
 useEffect(()=>bridge.back(()=>setScreen('home'),screen!=='home'&&screen!=='game'),[screen]);
 useEffect(()=>{if(!game?.current_question||feedback)return;setSeconds(game.current_question.timeout_seconds);const timer=window.setInterval(()=>setSeconds(value=>value<=1?0:value-1),1000);return()=>window.clearInterval(timer)},[game?.id,game?.current_question?.position,feedback]);
 useEffect(()=>{if(seconds===0&&game?.current_question&&!feedback)answer(-1)},[seconds]);
 const openGame=(data:Game,code='')=>{setGame(data);setChallengeCode(code);setFeedback('');bridge.fullscreen();setScreen('game')};
 const play=async(pack?:Pack)=>openGame(await api('/api/v1/games',{method:'POST',body:JSON.stringify({pack_slug:pack?.slug,category:'general',difficulty:'medium',question_count:pack?10:5})}));
 const daily=async()=>openGame(await api('/api/v1/daily/games',{method:'POST'}));
 const join=async(code:string)=>openGame(await api(`/api/v1/challenges/${encodeURIComponent(code)}/join`,{method:'POST'}),code);
 const challenge=async()=>{const data=await api('/api/v1/challenges',{method:'POST',body:JSON.stringify({category:'general',difficulty:'medium',question_count:5})});openGame(data.game,data.code)};
 const answer=async(index:number)=>{if(!game?.current_question||feedback)return;const result=await api(`/api/v1/games/${game.id}/answer`,{method:'POST',body:JSON.stringify({position:game.current_question.position,selected_index:index})});bridge.haptic(!!result.correct);setFeedback(result.correct?`✅ Верно! +${result.points}`:`❌ ${result.correct_answer}. ${result.explanation||''}`);if(result.game_over){setGame({...game,score:result.score,correct_answers:result.correct_answers,current_question:null});setTimeout(()=>{setScreen('result');refreshPlayer().catch(()=>{})},800)}else setGame({...game,score:result.score,correct_answers:result.correct_answers,current_question:result.next});};
 const next=()=>setFeedback(''); const accuracy=game?Math.round(100*game.correct_answers/Math.max(1,game.question_count)):0;
 return <main><header><b>⚔️ Quiz Battle</b><span>{ready?'🔥 Играй каждый день':'Загрузка…'}</span></header>{error&&<p className="feedback">{error}</p>}{screen==='home'&&<><section className="hero"><p>👋 Привет, {name}!</p><h1>Квиз дня</h1><p>7 вопросов · ~2 минуты</p><button onClick={daily}>ИГРАТЬ</button></section><div className="actions"><button onClick={()=>play()}>⚡ Быстрая игра</button><button onClick={challenge}>⚔️ Вызвать друга</button></div><h2>Популярные квизы</h2><div className="cards">{packs.slice(0,4).map(pack=><article key={pack.slug} onClick={()=>play(pack)}><i>{pack.emoji}</i><b>{pack.title}</b><small>{pack.question_count} вопросов · {pack.estimated_minutes} мин</small></article>)}</div></>}{screen==='catalog'&&<><h1>🗂 Квизы</h1><div className="cards all">{packs.map(pack=><article key={pack.slug} onClick={()=>play(pack)}><i>{pack.emoji}</i><b>{pack.title}</b><small>{pack.description}</small><small>10 вопросов · {pack.question_count} в pack</small></article>)}</div></>}{screen==='game'&&game?.current_question&&<section className="game"><div className="progress"><span>Вопрос {game.current_question.position+1}/{game.question_count} · ⏱ {seconds}с</span><b>⚡ {game.score}</b></div><h1>{game.current_question.text}</h1>{feedback?<div className="feedback"><p>{feedback}</p><button onClick={next}>Дальше →</button></div>:<div className="answers">{game.current_question.options.map((option,index)=><button key={option} onClick={()=>answer(index)}>{option}</button>)}</div>}</section>}{screen==='result'&&<section className="hero result"><p>🏆 Раунд завершён</p><h1>{game?.score} очков</h1><p>Точность: {accuracy}% · Прогресс сохранён</p><button onClick={()=>play()}>ЕЩЁ РАУНД</button><button onClick={()=>bridge.share(challengeCode?'⚔️ Прими мой вызов в Quiz Battle!':`Я набрал ${game?.score} очков в Quiz Battle!`,challengeCode||undefined)}>Поделиться</button></section>}{screen==='profile'&&<section><h1>👤 Профиль</h1><p>Освоение — 60% уникальные вопросы и 40% точность.</p>{mastery.length?mastery.map(item=><p className="mastery" key={item.category}>{item.category} <span>{'█'.repeat(Math.round(item.percent/10))}{'░'.repeat(10-Math.round(item.percent/10))} {item.percent}%</span></p>):<p>Сыграй первый раунд, чтобы увидеть освоение тем.</p>}<h2>Достижения</h2><p>{achievements.length?achievements.join(' · '):'Первый раунд уже ждёт тебя!'}</p></section>}{screen==='leaderboard'&&<section><h1>🏆 Лига недели</h1>{leaders.length?leaders.map(item=><p key={item.rank}>#{item.rank} {item.name} <b>{item.score}</b></p>):<p>Заверши Квиз дня и стань первым в лиге.</p>}</section>}{screen!=='game'&&<nav><button onClick={()=>setScreen('home')}>🏠<small>Главная</small></button><button onClick={()=>setScreen('catalog')}>🗂<small>Квизы</small></button><button onClick={()=>setScreen('leaderboard')}>🏆<small>Рейтинг</small></button><button onClick={()=>setScreen('profile')}>👤<small>Профиль</small></button></nav>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
