import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Tg={initData?:string;initDataUnsafe?:{user?:{first_name?:string}};BackButton?:{show():void;hide():void;onClick(fn:()=>void):void;offClick?(fn:()=>void):void};HapticFeedback?:{impactOccurred(x:string):void;notificationOccurred(x:string):void};themeParams?:Record<string,string>;requestFullscreen?():void;openTelegramLink?(url:string):void};
declare global {interface Window {WebApp?:Tg;Telegram?:{WebApp:Tg}}}
type Bridge={kind:'max'|'telegram'|'mock';initData():string;name():string;back(fn:()=>void,on:boolean):void;haptic(ok:boolean):void;fullscreen():void;share(text:string,token?:string):void};
const tg=()=>window.Telegram?.WebApp;
const platform=(import.meta.env.VITE_PLATFORM || (tg()?'telegram':window.WebApp?'max':'mock')) as Bridge['kind'];
const bridge:Bridge={kind:platform,initData:()=>platform==='telegram'?tg()?.initData||'':window.WebApp?.initData||'',name:()=>platform==='telegram'?tg()?.initDataUnsafe?.user?.first_name||'Игрок':window.WebApp?.initDataUnsafe?.user?.first_name||'Игрок',back:(fn,on)=>{const b=platform==='telegram'?tg()?.BackButton:window.WebApp?.BackButton;if(on){b?.show();b?.onClick(fn)}else b?.hide()},haptic:(ok)=>{const h=platform==='telegram'?tg()?.HapticFeedback:window.WebApp?.HapticFeedback;if(ok)h?.notificationOccurred('success');else h?.notificationOccurred('error')},fullscreen:()=>{if(platform==='telegram')tg()?.requestFullscreen?.()},share:(text,token)=>{const username=import.meta.env.VITE_TELEGRAM_BOT_USERNAME;const link=token&&username?`https://t.me/${username}?startapp=challenge_${encodeURIComponent(token)}`:'';if(platform==='telegram'&&link)tg()?.openTelegramLink?.(`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent(text)}`);else if(navigator.share)navigator.share({text,url:link}).catch(()=>{})}};
type Pack={slug:string;title:string;emoji:string;description:string;question_count:number;estimated_minutes:number};type Question={position:number;text:string;options:string[]};type Game={id:number;score:number;question_count:number;current_question:Question|null};
let session='';const headers=():Record<string,string>=>bridge.kind==='mock'?{'X-Development-User':'10001','Content-Type':'application/json'}:{Authorization:`Bearer ${session}`,'Content-Type':'application/json'};
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{...headers(),...(init?.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.json()}
function startParam(){return new URLSearchParams(location.search).get('tgWebAppStartParam')||new URLSearchParams(location.search).get('startapp')||''}
function App(){const [screen,setScreen]=useState<'home'|'catalog'|'game'|'result'|'profile'|'leaderboard'>('home'),[packs,setPacks]=useState<Pack[]>([]),[game,setGame]=useState<Game|null>(null),[feedback,setFeedback]=useState(''),[name,setName]=useState(bridge.name()),[error,setError]=useState(''),[challengeCode,setChallengeCode]=useState('');
useEffect(()=>{const load=async()=>{if(bridge.kind!=='mock'){const auth=await api(`/api/v1/auth/${bridge.kind}`,{method:'POST',body:JSON.stringify({init_data:bridge.initData()})});session=auth.access_token}const catalog=await api('/api/v1/quizzes');setPacks(catalog.items);setName((await api('/api/v1/me')).name);const p=startParam();if(p==='daily')await daily();else if(p.startsWith('challenge_'))await join(p.slice(10));else if(p==='leaderboard')setScreen('leaderboard')};load().catch(e=>setError('Не удалось подключиться к игре. Открой её из Telegram ещё раз.'))},[]);
useEffect(()=>{bridge.back(()=>setScreen('home'),screen!=='home'&&screen!=='game')},[screen]);
const play=async(pack?:Pack)=>{const data=await api('/api/v1/games',{method:'POST',body:JSON.stringify({pack_slug:pack?.slug,category:'general',difficulty:'medium',question_count:5})});setChallengeCode('');setGame(data);setFeedback('');bridge.fullscreen();setScreen('game')};
const daily=async()=>{const data=await api('/api/v1/daily/games',{method:'POST'});setGame(data);setFeedback('');bridge.fullscreen();setScreen('game')};
const join=async(code:string)=>{const data=await api(`/api/v1/challenges/${encodeURIComponent(code)}/join`,{method:'POST'});setGame(data);setFeedback('');bridge.fullscreen();setScreen('game')};
const challenge=async()=>{const data=await api('/api/v1/challenges',{method:'POST',body:JSON.stringify({category:'general',difficulty:'medium',question_count:5})});setChallengeCode(data.code);setGame(data.game);setFeedback('');bridge.fullscreen();setScreen('game');};
const answer=async(index:number)=>{if(!game?.current_question)return;const result=await api(`/api/v1/games/${game.id}/answer`,{method:'POST',body:JSON.stringify({position:game.current_question.position,selected_index:index})});bridge.haptic(!!result.correct);setFeedback(result.correct?`✅ Верно! +${result.points}`:`❌ ${result.correct_answer}. ${result.explanation||''}`);if(result.game_over){setGame({...game,score:result.score,current_question:null});setScreen('result')}else setGame({...game,score:result.score,current_question:result.next})};
return <main><header><b>⚔️ Quiz Battle</b><span>🔥 Играй каждый день</span></header>{error&&<p className="feedback">{error}</p>}{screen==='home'&&<><section className="hero"><p>👋 Привет, {name}!</p><h1>Квиз дня</h1><p>7 вопросов · ~2 минуты</p><button onClick={daily}>ИГРАТЬ</button></section><div className="actions"><button onClick={()=>play()}>⚡ Быстрая игра</button><button onClick={challenge}>⚔️ Вызвать друга</button></div><h2>Популярные квизы</h2><div className="cards">{packs.slice(0,4).map(p=><article key={p.slug} onClick={()=>play(p)}><i>{p.emoji}</i><b>{p.title}</b><small>{p.question_count} вопросов · {p.estimated_minutes} мин</small></article>)}</div></>}{screen==='catalog'&&<><h1>🗂 Квизы</h1><div className="cards all">{packs.map(p=><article key={p.slug} onClick={()=>play(p)}><i>{p.emoji}</i><b>{p.title}</b><small>{p.description}</small></article>)}</div></>}{screen==='game'&&game?.current_question&&<section className="game"><div className="progress"><span>Вопрос {game.current_question.position+1}/{game.question_count}</span><b>⚡ {game.score}</b></div><h1>{game.current_question.text}</h1><div className="answers">{game.current_question.options.map((x,i)=><button key={x} onClick={()=>answer(i)}>{x}</button>)}</div>{feedback&&<p className="feedback">{feedback}</p>}</section>}{screen==='result'&&<section className="hero result"><p>🏆 Раунд завершён</p><h1>{game?.score} очков</h1><p>Прогресс сохранён. Сможешь побить результат?</p><button onClick={()=>play()}>ЕЩЁ РАУНД</button><button onClick={()=>bridge.share(challengeCode?'⚔️ Прими мой вызов в Quiz Battle!':`Я набрал ${game?.score} очков в Quiz Battle!`,challengeCode||undefined)}>Поделиться</button></section>}{screen==='profile'&&<section><h1>👤 Профиль</h1><p>Твоя сила — каждый новый факт. Играй в разные темы, чтобы заполнить шкалы мастерства.</p></section>}{screen==='leaderboard'&&<section><h1>🏆 Лига недели</h1><p>Рейтинг обновляется после Квиза дня.</p></section>}{screen!=='game'&&<nav><button onClick={()=>setScreen('home')}>🏠<small>Главная</small></button><button onClick={()=>setScreen('catalog')}>🗂<small>Квизы</small></button><button onClick={()=>setScreen('profile')}>👤<small>Профиль</small></button></nav>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
